#!/bin/sh
# Installs ai-usage: a CLI launcher in ~/.local/bin, a starter config, the menu bar app with a
# login LaunchAgent, and (with --mcp) the MCP server registration for every agent CLI.
#
#   ./install.sh            CLI + menu bar app
#   ./install.sh --mcp      also register the MCP server with Claude Code, Codex and agy
#   ./install.sh --no-app   CLI only
set -eu

repo="$(cd "$(dirname "$0")" && pwd)"
with_app=1
with_mcp=0
for arg in "$@"; do
  case "$arg" in
    --no-app) with_app=0 ;;
    --mcp) with_mcp=1 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

node_bin="$(node -p process.execPath)"
launcher="$HOME/.local/bin/ai-usage"
mkdir -p "$HOME/.local/bin"
cat > "$launcher" <<EOF
#!/bin/sh
# Generated by $repo/install.sh
NODE="$node_bin"
[ -x "\$NODE" ] || NODE="\$(command -v node)" || { echo "ai-usage: node not found" >&2; exit 127; }
exec "\$NODE" "$repo/bin/ai-usage.mjs" "\$@"
EOF
chmod 755 "$launcher"
echo "✓ launcher: $launcher (node: $node_bin)"

config="${AI_USAGE_CONFIG:-$HOME/.config/ai-usage/config.json}"
if [ ! -f "$config" ]; then
  "$launcher" init
else
  echo "• config exists: $config"
fi

# Skill for harnesses without the Claude/Codex plugin system: ~/.agents/skills is the hub (Gemini CLI reads it
# directly); agy and OpenCode get a link to it. Claude Code and Codex get the skill from the plugin.
# Point $2 at $1. Replaces an old or dangling link (e.g. after moving the checkout), never a real file or directory.
link() {
  if [ -L "$2" ] || [ ! -e "$2" ]; then
    ln -sfn "$1" "$2"
  else
    echo "• $2 exists and is not a link; left alone" >&2
  fi
}
skill_hub="$HOME/.agents/skills/ai-usage"
mkdir -p "$HOME/.agents/skills"
link "$repo/skills/ai-usage" "$skill_hub"
for dir in "$HOME/.gemini/config/skills" "$HOME/.config/opencode/skills"; do
  parent="$(dirname "$dir")"
  [ -d "$parent" ] || continue
  mkdir -p "$dir"
  link "$skill_hub" "$dir/ai-usage"
done
echo "✓ skill linked: $skill_hub (+ agy and OpenCode where installed)"

if [ "$with_app" = 1 ] && [ "$(uname)" != Darwin ]; then
  echo "• skipping the menu bar app (macOS only); use 'ai-usage watch' instead"
  with_app=0
fi

if [ "$with_app" = 1 ]; then
  app="$HOME/Applications/AI Usage.app"
  AI_USAGE_COMMAND="$launcher" "$repo/macos/build.sh" "$app"
  plist="$HOME/Library/LaunchAgents/local.ai-usage.bar.plist"
  mkdir -p "$(dirname "$plist")"
  cat > "$plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>local.ai-usage.bar</string>
  <key>ProgramArguments</key><array><string>$app/Contents/MacOS/AIUsageBar</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><dict><key>SuccessfulExit</key><false/></dict>
  <key>ProcessType</key><string>Interactive</string>
</dict>
</plist>
EOF
  service="gui/$(id -u)/local.ai-usage.bar"
  launchctl bootout "$service" 2>/dev/null || true
  # bootout returns before the old instance is gone; bootstrapping too early fails with "5: Input/output error".
  tries=0
  while launchctl print "$service" >/dev/null 2>&1 && [ "$tries" -lt 50 ]; do sleep 0.1; tries=$((tries + 1)); done
  launchctl bootstrap "gui/$(id -u)" "$plist"
  echo "✓ menu bar app running and set to start at login ($plist)"
fi

if [ "$with_mcp" = 1 ]; then
  "$launcher" mcp-install
fi
